// <auto-generated />
using System;
using AquaGuard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquaGuard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618013443_EnumsAsString")]
    partial class EnumsAsString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AquaGuard.API.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MedidorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("MedidorId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("AquaGuard.API.Models.LeituraConsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("datetime2");

                    b.Property<double>("LitrosConsumidos")
                        .HasColumnType("float");

                    b.Property<int>("MedidorId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedidorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Leituras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataLeitura = new DateTime(2024, 5, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            LitrosConsumidos = 1200.0,
                            MedidorId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            DataLeitura = new DateTime(2024, 5, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            LitrosConsumidos = 1350.0,
                            MedidorId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            DataLeitura = new DateTime(2024, 5, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            LitrosConsumidos = 900.0,
                            MedidorId = 2,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("AquaGuard.API.Models.Medidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<double>("LimiteMensalLitros")
                        .HasColumnType("float");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Medidores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "MED-001",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimiteMensalLitros = 50000.0,
                            Localizacao = "Bloco A - Térreo"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "MED-002",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimiteMensalLitros = 30000.0,
                            Localizacao = "Bloco B - 1º Andar"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Codigo = "MED-003",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LimiteMensalLitros = 20000.0,
                            Localizacao = "Área Externa - Jardim"
                        });
                });

            modelBuilder.Entity("AquaGuard.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@aquaguard.com",
                            Nome = "Administrador",
                            Role = "Admin",
                            SenhaHash = "$2a$11$UqHxm4TEWJnapK3OYO.TFebvxIX4GwqqTreA6aeDBvI3YTq3llliC"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "operador@aquaguard.com",
                            Nome = "Operador Padrão",
                            Role = "Operador",
                            SenhaHash = "$2a$11$S/IXoxQZvha8aJEw8gbLO.2KBPe1TIiPF2bPvpcxHy4dPo1AlAZPS"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "auditor@aquaguard.com",
                            Nome = "Auditor Padrão",
                            Role = "Auditor",
                            SenhaHash = "$2a$11$LKHsuckj4ukwS1JFN75qv.piZQ4EvcylSes3MIiSEVesrXLssEPlC"
                        });
                });

            modelBuilder.Entity("AquaGuard.API.Models.Alerta", b =>
                {
                    b.HasOne("AquaGuard.API.Models.Medidor", "Medidor")
                        .WithMany("Alertas")
                        .HasForeignKey("MedidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medidor");
                });

            modelBuilder.Entity("AquaGuard.API.Models.LeituraConsumo", b =>
                {
                    b.HasOne("AquaGuard.API.Models.Medidor", "Medidor")
                        .WithMany("Leituras")
                        .HasForeignKey("MedidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquaGuard.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medidor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AquaGuard.API.Models.Medidor", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
